### ISSUE TITLE
Cannot GET

### ISSUE THREAD

**Issue by StarLabsUA** [raidendotai/cofounder#1]
Hallo, Generation spent 13$ balance gpt api and it does not work, and for some reason the port is 1337, not 5173.

![image](https://github.com/user-attachments/assets/bd3a2371-b3c4-4deb-ab0b-f33ee204e4c6)

log file include
[2024-10-03T20_34_52_188Z-debug-0.log](https://github.com/user-attachments/files/17249821/2024-10-03T20_34_52_188Z-debug-0.log)

[2024-10-03T20_38_46_975Z-debug-0.log](https://github.com/user-attachments/files/17249870/2024-10-03T20_38_46_975Z-debug-0.log)

**Comment by raidendotai** [comment]
- `1337` is the server port, `5173` is the vite+react app port
- from your logs, the issue is related to conflicting versions in installed packages (`react-day-picker` & `date-fns`), which stops the server from starting
- if you have trouble debugging issues like the above, I'd suggest waiting for v1 after the alpha release
  we're expecting to have debugging features by then and fewer technical barriers/eventualities (ideally none at all !)
- until then, remember you're dealing with a highly experimental generative software project :)

**Comment by StarLabsUA** [comment]
But I have the right versions installed, I checked.
